
export const mockStoreItems = [
  {
    id: 'pro-coach',
    name: 'Статус "Тренер"',
    description: 'Разблокируйте доступ к AI-аналитике матчей и расширенному управлению командой.',
    category: 'PRO-статусы',
    price: 15000,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'coach clipboard strategy',
    type: 'pro_status',
  },
  {
    id: 'pro-manager',
    name: 'Статус "Менеджер"',
    description: 'Получите инструменты для управления несколькими командами и игроками, а также доступ к трансферному рынку.',
    category: 'PRO-статусы',
    price: 25000,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'business handshake deal',
    type: 'pro_status',
  },
  {
    id: 'item-1',
    name: 'Золотая рамка "Чемпион"',
    description: 'Покажите всем, кто здесь победитель.',
    category: 'Рамки для аватара',
    price: 500,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'gold frame',
    type: 'cosmetic',
  },
  {
    id: 'item-2',
    name: 'Эффект "Горящий мяч"',
    description: 'Анимированный эффект для страницы команды.',
    category: 'Эффекты для профиля',
    price: 1200,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'fireball',
    type: 'effect',
  },
  {
    id: 'item-3',
    name: 'Рамка "Неоновый киберпанк"',
    description: 'Стильная анимированная рамка для аватара.',
    category: 'Рамки для аватара',
    price: 750,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'neon frame',
    type: 'cosmetic',
  },
  {
    id: 'item-4',
    name: 'Эффект "Легендарное сияние"',
    description: 'Золотое свечение вокруг вашего профиля.',
    category: 'Эффекты для профиля',
    price: 1500,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'gold aura',
    type: 'effect',
  },
  {
    id: 'item-5',
    name: 'Пак из 5 генераций лого',
    description: '+5 попыток для AI-генератора логотипов.',
    category: 'Бустеры',
    price: 300,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'logo pack',
    type: 'consumable',
    quantity: 5,
  },
   {
    id: 'item-6',
    name: 'Бустер опыта x2 (3 дня)',
    description: 'Удваивает получаемый опыт на 72 часа.',
    category: 'Бустеры',
    price: 400,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'xp boost',
    type: 'consumable',
    quantity: 1,
  },
];
