/* tslint:disable */
/* eslint-disable */
/**
 * Sport Matching API
 * A RESTful API for a sports team and player matching platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'details'?: string;
}
/**
 * 
 * @export
 * @interface NewPlayground
 */
export interface NewPlayground {
    /**
     * 
     * @type {string}
     * @memberof NewPlayground
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NewPlayground
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof NewPlayground
     */
    'surface'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewPlayground
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface NewPost
 */
export interface NewPost {
    /**
     * 
     * @type {string}
     * @memberof NewPost
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof NewPost
     */
    'teamId'?: string;
}
/**
 * 
 * @export
 * @interface NewSport
 */
export interface NewSport {
    /**
     * 
     * @type {string}
     * @memberof NewSport
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof NewSport
     */
    'isTeamSport': boolean;
}
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'per_page'?: number;
}
/**
 * 
 * @export
 * @interface Playground
 */
export interface Playground {
    /**
     * 
     * @type {string}
     * @memberof Playground
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Playground
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Playground
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof Playground
     */
    'surface'?: string;
    /**
     * 
     * @type {string}
     * @memberof Playground
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'teamId'?: string;
}
/**
 * 
 * @export
 * @interface Sport
 */
export interface Sport {
    /**
     * 
     * @type {string}
     * @memberof Sport
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Sport
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Sport
     */
    'isTeamSport'?: boolean;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatarUrl'?: string;
}

/**
 * PlaygroundsApi - axios parameter creator
 * @export
 */
export const PlaygroundsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all playgrounds
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PlaygroundsGet: async (page?: number, perPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/playgrounds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new playground
         * @param {NewPlayground} newPlayground 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PlaygroundsPost: async (newPlayground: NewPlayground, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newPlayground' is not null or undefined
            assertParamExists('apiV1PlaygroundsPost', 'newPlayground', newPlayground)
            const localVarPath = `/api/v1/playgrounds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newPlayground, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlaygroundsApi - functional programming interface
 * @export
 */
export const PlaygroundsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlaygroundsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all playgrounds
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PlaygroundsGet(page?: number, perPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PlaygroundsGet(page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlaygroundsApi.apiV1PlaygroundsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new playground
         * @param {NewPlayground} newPlayground 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PlaygroundsPost(newPlayground: NewPlayground, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PlaygroundsPost(newPlayground, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlaygroundsApi.apiV1PlaygroundsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PlaygroundsApi - factory interface
 * @export
 */
export const PlaygroundsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlaygroundsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all playgrounds
         * @param {PlaygroundsApiApiV1PlaygroundsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PlaygroundsGet(requestParameters: PlaygroundsApiApiV1PlaygroundsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.apiV1PlaygroundsGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new playground
         * @param {PlaygroundsApiApiV1PlaygroundsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PlaygroundsPost(requestParameters: PlaygroundsApiApiV1PlaygroundsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1PlaygroundsPost(requestParameters.newPlayground, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1PlaygroundsGet operation in PlaygroundsApi.
 * @export
 * @interface PlaygroundsApiApiV1PlaygroundsGetRequest
 */
export interface PlaygroundsApiApiV1PlaygroundsGetRequest {
    /**
     * 
     * @type {number}
     * @memberof PlaygroundsApiApiV1PlaygroundsGet
     */
    readonly page?: number;

    /**
     * 
     * @type {number}
     * @memberof PlaygroundsApiApiV1PlaygroundsGet
     */
    readonly perPage?: number;
}

/**
 * Request parameters for apiV1PlaygroundsPost operation in PlaygroundsApi.
 * @export
 * @interface PlaygroundsApiApiV1PlaygroundsPostRequest
 */
export interface PlaygroundsApiApiV1PlaygroundsPostRequest {
    /**
     * 
     * @type {NewPlayground}
     * @memberof PlaygroundsApiApiV1PlaygroundsPost
     */
    readonly newPlayground: NewPlayground;
}

/**
 * PlaygroundsApi - object-oriented interface
 * @export
 * @class PlaygroundsApi
 * @extends {BaseAPI}
 */
export class PlaygroundsApi extends BaseAPI {
    /**
     * 
     * @summary Get all playgrounds
     * @param {PlaygroundsApiApiV1PlaygroundsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlaygroundsApi
     */
    public apiV1PlaygroundsGet(requestParameters: PlaygroundsApiApiV1PlaygroundsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return PlaygroundsApiFp(this.configuration).apiV1PlaygroundsGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new playground
     * @param {PlaygroundsApiApiV1PlaygroundsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlaygroundsApi
     */
    public apiV1PlaygroundsPost(requestParameters: PlaygroundsApiApiV1PlaygroundsPostRequest, options?: RawAxiosRequestConfig) {
        return PlaygroundsApiFp(this.configuration).apiV1PlaygroundsPost(requestParameters.newPlayground, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * PostsApi - axios parameter creator
 * @export
 */
export const PostsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all posts
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PostsGet: async (page?: number, perPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new post
         * @param {NewPost} newPost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PostsPost: async (newPost: NewPost, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newPost' is not null or undefined
            assertParamExists('apiV1PostsPost', 'newPost', newPost)
            const localVarPath = `/api/v1/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newPost, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PostsApi - functional programming interface
 * @export
 */
export const PostsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PostsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all posts
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PostsGet(page?: number, perPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PostsGet(page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PostsApi.apiV1PostsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new post
         * @param {NewPost} newPost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PostsPost(newPost: NewPost, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PostsPost(newPost, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PostsApi.apiV1PostsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PostsApi - factory interface
 * @export
 */
export const PostsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PostsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all posts
         * @param {PostsApiApiV1PostsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PostsGet(requestParameters: PostsApiApiV1PostsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.apiV1PostsGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new post
         * @param {PostsApiApiV1PostsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PostsPost(requestParameters: PostsApiApiV1PostsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1PostsPost(requestParameters.newPost, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1PostsGet operation in PostsApi.
 * @export
 * @interface PostsApiApiV1PostsGetRequest
 */
export interface PostsApiApiV1PostsGetRequest {
    /**
     * 
     * @type {number}
     * @memberof PostsApiApiV1PostsGet
     */
    readonly page?: number;

    /**
     * 
     * @type {number}
     * @memberof PostsApiApiV1PostsGet
     */
    readonly perPage?: number;
}

/**
 * Request parameters for apiV1PostsPost operation in PostsApi.
 * @export
 * @interface PostsApiApiV1PostsPostRequest
 */
export interface PostsApiApiV1PostsPostRequest {
    /**
     * 
     * @type {NewPost}
     * @memberof PostsApiApiV1PostsPost
     */
    readonly newPost: NewPost;
}

/**
 * PostsApi - object-oriented interface
 * @export
 * @class PostsApi
 * @extends {BaseAPI}
 */
export class PostsApi extends BaseAPI {
    /**
     * 
     * @summary Get all posts
     * @param {PostsApiApiV1PostsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApi
     */
    public apiV1PostsGet(requestParameters: PostsApiApiV1PostsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return PostsApiFp(this.configuration).apiV1PostsGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new post
     * @param {PostsApiApiV1PostsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApi
     */
    public apiV1PostsPost(requestParameters: PostsApiApiV1PostsPostRequest, options?: RawAxiosRequestConfig) {
        return PostsApiFp(this.configuration).apiV1PostsPost(requestParameters.newPost, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * SportsApi - axios parameter creator
 * @export
 */
export const SportsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all sports
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1SportsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new sport
         * @param {NewSport} newSport 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1SportsPost: async (newSport: NewSport, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newSport' is not null or undefined
            assertParamExists('apiV1SportsPost', 'newSport', newSport)
            const localVarPath = `/api/v1/sports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newSport, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SportsApi - functional programming interface
 * @export
 */
export const SportsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SportsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all sports
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1SportsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Sport>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1SportsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SportsApi.apiV1SportsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new sport
         * @param {NewSport} newSport 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1SportsPost(newSport: NewSport, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1SportsPost(newSport, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SportsApi.apiV1SportsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SportsApi - factory interface
 * @export
 */
export const SportsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SportsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all sports
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1SportsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Sport>> {
            return localVarFp.apiV1SportsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new sport
         * @param {SportsApiApiV1SportsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1SportsPost(requestParameters: SportsApiApiV1SportsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1SportsPost(requestParameters.newSport, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1SportsPost operation in SportsApi.
 * @export
 * @interface SportsApiApiV1SportsPostRequest
 */
export interface SportsApiApiV1SportsPostRequest {
    /**
     * 
     * @type {NewSport}
     * @memberof SportsApiApiV1SportsPost
     */
    readonly newSport: NewSport;
}

/**
 * SportsApi - object-oriented interface
 * @export
 * @class SportsApi
 * @extends {BaseAPI}
 */
export class SportsApi extends BaseAPI {
    /**
     * 
     * @summary Get all sports
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SportsApi
     */
    public apiV1SportsGet(options?: RawAxiosRequestConfig) {
        return SportsApiFp(this.configuration).apiV1SportsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new sport
     * @param {SportsApiApiV1SportsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SportsApi
     */
    public apiV1SportsPost(requestParameters: SportsApiApiV1SportsPostRequest, options?: RawAxiosRequestConfig) {
        return SportsApiFp(this.configuration).apiV1SportsPost(requestParameters.newSport, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UploadsApi - axios parameter creator
 * @export
 */
export const UploadsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Complete a file upload
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1UploadsCompletePost: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('apiV1UploadsCompletePost', 'body', body)
            const localVarPath = `/api/v1/uploads/complete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Initiate a file upload
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1UploadsInitiatePost: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('apiV1UploadsInitiatePost', 'body', body)
            const localVarPath = `/api/v1/uploads/initiate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UploadsApi - functional programming interface
 * @export
 */
export const UploadsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UploadsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Complete a file upload
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1UploadsCompletePost(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1UploadsCompletePost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadsApi.apiV1UploadsCompletePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Initiate a file upload
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1UploadsInitiatePost(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1UploadsInitiatePost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadsApi.apiV1UploadsInitiatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UploadsApi - factory interface
 * @export
 */
export const UploadsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UploadsApiFp(configuration)
    return {
        /**
         * 
         * @summary Complete a file upload
         * @param {UploadsApiApiV1UploadsCompletePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1UploadsCompletePost(requestParameters: UploadsApiApiV1UploadsCompletePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.apiV1UploadsCompletePost(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Initiate a file upload
         * @param {UploadsApiApiV1UploadsInitiatePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1UploadsInitiatePost(requestParameters: UploadsApiApiV1UploadsInitiatePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.apiV1UploadsInitiatePost(requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1UploadsCompletePost operation in UploadsApi.
 * @export
 * @interface UploadsApiApiV1UploadsCompletePostRequest
 */
export interface UploadsApiApiV1UploadsCompletePostRequest {
    /**
     * 
     * @type {object}
     * @memberof UploadsApiApiV1UploadsCompletePost
     */
    readonly body: object;
}

/**
 * Request parameters for apiV1UploadsInitiatePost operation in UploadsApi.
 * @export
 * @interface UploadsApiApiV1UploadsInitiatePostRequest
 */
export interface UploadsApiApiV1UploadsInitiatePostRequest {
    /**
     * 
     * @type {object}
     * @memberof UploadsApiApiV1UploadsInitiatePost
     */
    readonly body: object;
}

/**
 * UploadsApi - object-oriented interface
 * @export
 * @class UploadsApi
 * @extends {BaseAPI}
 */
export class UploadsApi extends BaseAPI {
    /**
     * 
     * @summary Complete a file upload
     * @param {UploadsApiApiV1UploadsCompletePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApi
     */
    public apiV1UploadsCompletePost(requestParameters: UploadsApiApiV1UploadsCompletePostRequest, options?: RawAxiosRequestConfig) {
        return UploadsApiFp(this.configuration).apiV1UploadsCompletePost(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Initiate a file upload
     * @param {UploadsApiApiV1UploadsInitiatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApi
     */
    public apiV1UploadsInitiatePost(requestParameters: UploadsApiApiV1UploadsInitiatePostRequest, options?: RawAxiosRequestConfig) {
        return UploadsApiFp(this.configuration).apiV1UploadsInitiatePost(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get current user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1UsersMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get current user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1UsersMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1UsersMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiV1UsersMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Get current user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1UsersMeGet(options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.apiV1UsersMeGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Get current user\'s profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiV1UsersMeGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiV1UsersMeGet(options).then((request) => request(this.axios, this.basePath));
    }
}
