/* tslint:disable */
/* eslint-disable */
/**
 * Sport Matching API
 * A RESTful API for a sports team and player matching platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * 
     * @type {string}
     * @memberof ApiError
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface ApiV1AuthLoginPostRequest
 */
export interface ApiV1AuthLoginPostRequest {
    /**
     * User\'s email
     * @type {string}
     * @memberof ApiV1AuthLoginPostRequest
     */
    'email': string;
    /**
     * User\'s password
     * @type {string}
     * @memberof ApiV1AuthLoginPostRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ApiV1AuthLogoutPostRequest
 */
export interface ApiV1AuthLogoutPostRequest {
    /**
     * The refresh token
     * @type {string}
     * @memberof ApiV1AuthLogoutPostRequest
     */
    'refreshToken': string;
}
/**
 * 
 * @export
 * @interface ApiV1AuthRegisterPostRequest
 */
export interface ApiV1AuthRegisterPostRequest {
    /**
     * User\'s city
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    'city'?: string;
    /**
     * User\'s email
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    'email': string;
    /**
     * User\'s first name
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    'firstName'?: string;
    /**
     * User\'s last name
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    'lastName'?: string;
    /**
     * User\'s nickname
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    'nickname': string;
    /**
     * User\'s password
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    'password': string;
    /**
     * User\'s role
     * @type {string}
     * @memberof ApiV1AuthRegisterPostRequest
     */
    'role': string;
}
/**
 * 
 * @export
 * @interface ApiV1PlaygroundsPostRequest
 */
export interface ApiV1PlaygroundsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1PlaygroundsPostRequest
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PlaygroundsPostRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PlaygroundsPostRequest
     */
    'surface': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PlaygroundsPostRequest
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ApiV1PostsPostIdCommentsPostRequest
 */
export interface ApiV1PostsPostIdCommentsPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1PostsPostIdCommentsPostRequest
     */
    'authorId': number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PostsPostIdCommentsPostRequest
     */
    'text': string;
}
/**
 * 
 * @export
 * @interface ApiV1PostsPostRequest
 */
export interface ApiV1PostsPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1PostsPostRequest
     */
    'authorId': number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PostsPostRequest
     */
    'content': string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1PostsPostRequest
     */
    'teamId'?: number;
}
/**
 * 
 * @export
 * @interface ApiV1SponsorsPostRequest
 */
export interface ApiV1SponsorsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SponsorsPostRequest
     */
    'contribution': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SponsorsPostRequest
     */
    'logoUrl': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SponsorsPostRequest
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ApiV1SportsPostRequest
 */
export interface ApiV1SportsPostRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1SportsPostRequest
     */
    'isTeamSport': boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SportsPostRequest
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ApiV1TeamsPostRequest
 */
export interface ApiV1TeamsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    'logoUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TeamsPostRequest
     */
    'sport_id': string;
}
/**
 * 
 * @export
 * @interface ApiV1TeamsTeamIdApplicationsUserIdRespondPostRequest
 */
export interface ApiV1TeamsTeamIdApplicationsUserIdRespondPostRequest {
    /**
     * accept or decline
     * @type {string}
     * @memberof ApiV1TeamsTeamIdApplicationsUserIdRespondPostRequest
     */
    'action': string;
}
/**
 * 
 * @export
 * @interface ApiV1TournamentsPostRequest
 */
export interface ApiV1TournamentsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1TournamentsPostRequest
     */
    'game': string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1TournamentsPostRequest
     */
    'maxParticipants': number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TournamentsPostRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TournamentsPostRequest
     */
    'startDate': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1TournamentsPostRequest
     */
    'status': string;
}
/**
 * 
 * @export
 * @interface ApiV1UsersPostRequest
 */
export interface ApiV1UsersPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1UsersPostRequest
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'nickname': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersPostRequest
     */
    'role': string;
}
/**
 * 
 * @export
 * @interface ApiV1UsersUserIdPutRequest
 */
export interface ApiV1UsersUserIdPutRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'avatarUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'bio'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'coverImageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'phone'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1UsersUserIdPutRequest
     */
    'sports'?: Array<string>;
}
/**
 * 
 * @export
 * @interface ApplicationResponse
 */
export interface ApplicationResponse {
    /**
     * 
     * @type {string}
     * @memberof ApplicationResponse
     */
    'action': string;
}
/**
 * 
 * @export
 * @interface FollowToggleResponse
 */
export interface FollowToggleResponse {
    /**
     * 
     * @type {boolean}
     * @memberof FollowToggleResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FollowToggleResponse
     */
    'isFollowing'?: boolean;
}
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'accessToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'refreshToken'?: string;
    /**
     * 
     * @type {User}
     * @memberof LoginResponse
     */
    'user'?: User;
}
/**
 * 
 * @export
 * @interface NewSport
 */
export interface NewSport {
    /**
     * 
     * @type {string}
     * @memberof NewSport
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof NewSport
     */
    'isTeamSport': boolean;
}
/**
 * 
 * @export
 * @interface NewTeam
 */
export interface NewTeam {
    /**
     * 
     * @type {string}
     * @memberof NewTeam
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NewTeam
     */
    'sport_id': string;
    /**
     * 
     * @type {string}
     * @memberof NewTeam
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof NewTeam
     */
    'logoUrl'?: string;
}
/**
 * 
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'nickname': string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'role': string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'lastName': string;
    /**
     * 
     * @type {number}
     * @memberof NewUser
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    'gender'?: string;
}
/**
 * 
 * @export
 * @interface Sport
 */
export interface Sport {
    /**
     * 
     * @type {string}
     * @memberof Sport
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Sport
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Sport
     */
    'isTeamSport'?: boolean;
}
/**
 * 
 * @export
 * @interface SuccessResponse
 */
export interface SuccessResponse {
    /**
     * 
     * @type {string}
     * @memberof SuccessResponse
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'logoUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'city'?: string;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    'captainId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'sport_id'?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof Team
     */
    'members'?: Array<User>;
    /**
     * 
     * @type {User}
     * @memberof Team
     */
    'captain'?: User;
}
/**
 * 
 * @export
 * @interface TokenRefreshResponse
 */
export interface TokenRefreshResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshResponse
     */
    'accessToken'?: string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatarUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'role'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastName'?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'bio'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'coverImageUrl'?: string;
}
/**
 * 
 * @export
 * @interface UserSession
 */
export interface UserSession {
    /**
     * 
     * @type {string}
     * @memberof UserSession
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserSession
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserSession
     */
    'ipAddress'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserSession
     */
    'isCurrent'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserSession
     */
    'lastActiveAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSession
     */
    'userAgent'?: string;
}
/**
 * 
 * @export
 * @interface UserUpdate
 */
export interface UserUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'gender'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserUpdate
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'bio'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserUpdate
     */
    'sports'?: Array<string>;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary User Login (JWT)
         * @param {UserLogin} userLogin 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (userLogin: UserLogin, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userLogin' is not null or undefined
            assertParamExists('authLoginPost', 'userLogin', userLogin)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userLogin, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {UserRegistration} userRegistration 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost: async (userRegistration: UserRegistration, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userRegistration' is not null or undefined
            assertParamExists('authRegisterPost', 'userRegistration', userRegistration)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userRegistration, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary User Login (JWT)
         * @param {UserLogin} userLogin 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(userLogin: UserLogin, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(userLogin, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRefreshPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenRefreshResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRefreshPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRefreshPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register a new user
         * @param {UserRegistration} userRegistration 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRegisterPost(userRegistration: UserRegistration, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRegisterPost(userRegistration, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary User Login (JWT)
         * @param {AuthApiAuthLoginPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(requestParameters: AuthApiAuthLoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.authLoginPost(requestParameters.userLogin, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.authLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshPost(options?: RawAxiosRequestConfig): AxiosPromise<TokenRefreshResponse> {
            return localVarFp.authRefreshPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new user
         * @param {AuthApiAuthRegisterPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost(requestParameters: AuthApiAuthRegisterPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.authRegisterPost(requestParameters.userRegistration, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for authLoginPost operation in AuthApi.
 * @export
 * @interface AuthApiAuthLoginPostRequest
 */
export interface AuthApiAuthLoginPostRequest {
    /**
     * 
     * @type {UserLogin}
     * @memberof AuthApiAuthLoginPost
     */
    readonly userLogin: UserLogin
}

/**
 * Request parameters for authRegisterPost operation in AuthApi.
 * @export
 * @interface AuthApiAuthRegisterPostRequest
 */
export interface AuthApiAuthRegisterPostRequest {
    /**
     * 
     * @type {UserRegistration}
     * @memberof AuthApiAuthRegisterPost
     */
    readonly userRegistration: UserRegistration
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary User Login (JWT)
     * @param {AuthApiAuthLoginPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLoginPost(requestParameters: AuthApiAuthLoginPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginPost(requestParameters.userLogin, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLogoutPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authRefreshPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRefreshPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a new user
     * @param {AuthApiAuthRegisterPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authRegisterPost(requestParameters: AuthApiAuthRegisterPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRegisterPost(requestParameters.userRegistration, options).then((request) => request(this.axios, this.basePath));
    }
}
