/* tslint:disable */
/* eslint-disable */
/**
 * Prodvor Backend API
 * API for the Prodvor sports-oriented social platform. This documentation is auto-generated and reflects the current state of the backend routes.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

